# set default options
set -g mouse on
set -g base-index 1
set -g escape-time 0
set -g repeat-time 1000
set -g pane-base-index 1
set -g history-limit 100000
set-option -g renumber-windows on
set-window-option -g pane-base-index 1
set-option -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB"
set -as terminal-features ",ghostty:RGB"
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta,bright
set -g extended-keys on
set -g extended-keys-format csi-u

# status bar
set -g status-position bottom

# source tmux
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# set prefix
unbind C-b
set -g prefix M-a
bind M-a send-prefix

# detach
set -g detach-on-destroy off
set -g set-clipboard on
set -g allow-passthrough on

# Windows Title
set-option -g automatic-rename on
set-window-option -g mode-keys vi
unbind -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "wl-clipboard"
bind-key -T prefix t set-option -g status

# Open panes in current directory
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind-key x kill-pane

# search Windows
bind M-f display-popup -E "\
  tmux list-windows -F '#{window_index} #{window_name}' |\
  sed '/^$/d' |\
  fzf --reverse --header jump-to-window |\
  cut -d ' ' -f 1 |\
  xargs tmux select-window -t"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

bind-key "k" run-shell "sesh connect \"$(
  sesh list --icons | fzf \
    --no-sort --ansi --border-label ' sesh ' \
    --header '  ^a all ^t tmux ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(  )+reload(sesh list --icons)' \
    --preview-window 'right:45%' \
    --preview 'if [ -d {2..} ]; then eza --tree --level 2 --icons --color=always {2..}; else sesh preview {}; fi' \
    --color=bg+:#1e1e2e,spinner:#7dcfff,hl:#73daca \
    --color=fg:#cdd6f4,header:#73daca,info:#cba6f7,pointer:#e0af68 \
    --color=marker:#7dcfff,fg+:#cdd6f4,prompt:#cba6f7,hl+:#73daca \
    --height=60% --tmux 80% --border --prompt ' ' --pointer '»' --marker '⇒'
)\""

bind -N "switch to root session (via sesh) " 9 run-shell "sesh connect --root #{pane_current_path}"

bind-key L run-shell "~/.config/tmux/layouts/dev.sh"

# source
source-file ~/.config/tmux/minimal.conf
run ~/.config/tmux/plugins/tpm/tpm
