source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/colorscheme.conf
source = ~/.config/hypr/modules/inputs.conf
source = ~/.config/hypr/modules/animation.conf
source = ~/.config/hypr/modules/groups.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/customization.conf
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/workspacerules.conf
source = ~/.config/hypr/modules/plugins.conf

