# Maximum allowed gamma (optional, default is 1.0)
max-gamma = 1.0

# DAYTIME: Normal colors
profile {
    time = 07:00
    identity = true   # Disables the blue light filter
    gamma = 1.0
}

# EVENING: Warm colors
profile {
    time = 19:00
    temperature = 4500
    gamma = 0.9       # Slightly dims the screen too
}

