# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █░█ ██▄ █▄▄

exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all

exec-once = waybar
exec-once = awww-daemon && sleep 0.1 && awww restore
exec-once = swaync
exec-once = clipse -listen
exec-once = hypridle
exec-once = udiskie &
exec-once = hyprsunset
exec-once = /usr/lib/soteria-polkit/soteria
exec-once = hyprctl setcursor Bibata-Modern-Ice 22
exec-once = ~/.config/hypr/scripts/power_monitor.sh
exec-once = hyprpm reload -n
exec-once = foot --server
