general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgb($mauve)
    col.inactive_border = rgb($transparent)
    resize_on_border = true
    allow_tearing = true
    layout = dwindle
}

decoration {
    rounding = 5
    active_opacity = 0.90
    inactive_opacity = 0.75

    blur {
      enabled = true
      passes = 2
      size = 8
      vibrancy = 0.1696
    }
}


# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

dwindle {
    pseudotile = true
    preserve_split = true
}


# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    font_family = "Poppins"
    vfr = true
    vrr = 1
}


xwayland {
  force_zero_scaling = true
}
