group {
  col.border_active = rgb($lavender)
  col.border_inactive = rgba(1e1e2eaa)

groupbar {
# Font settings
  font_family = "JetBrainsMono Nerd Font"
  font_size = 12

        # Colors
  col.active = rgb($lavender)
  col.inactive = rgb($base)
        
        # Text colors (Requires Hyprland v0.42.0+)
  text_color = rgb($crust)
        
        # Appearance
  gradients = true
  render_titles = true
  height = 14
  stacked = false # Set to true for a vertical stack
  blur = true
  }
}

# Toggle a window into/out of a group
bind = SUPER, G, togglegroup

# Navigation (Switch between tabs/windows in the group)
bind = SUPER, TAB, changegroupactive, f # forward
bind = SUPER_SHIFT, TAB, changegroupactive, b # backward

# Move windows into/out of groups
bind = SUPER_SHIFT, G, moveoutofgroup
