plugin {
  easymotion {
    textsize=50
    textcolor=rgba(000000ff)
    bgcolor=rgba(a6e3a1aa)
    blur=0
    blurA=1.0
    xray=0
    textfont=Poppins
    textpadding=10
    bordersize=5
    bordercolor=rgba(1e1e2eff)
    rounding=5
    fullscreen_action=none
    motionkeys=abcdefghijklmnopqrstuvwxyz1234567890
    motionlabels=ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
    only_special = true
  }
}
