# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

windowrule = float true, center true, size 900 500,match:class blueman-manager
windowrule = float true, center true, size 900 500,match:title ^(Network Connections)$
windowrule = float true, center true, size 900 600,match:title ^(Volume Control)$
windowrule = float true, center true, size 800 600,match:title ^(Waypaper)$
windowrule = float true, center true, size 900 700,match:title ^(Zed — Settings)$

# --------------------------------------------------------
# Common Dialog Windows
# --------------------------------------------------------
windowrule = float true, center true, size 700 500,match:title ^(Open.*Files?|Save.*Files?|All Files|Save)$
windowrule = float true, center true, size 700 500,match:title ^(Save).*$
# Rename dialogs
windowrule = float true, center true, size 350 100,match:title ^(Rename|Move).*$

# Generic dialog windows
windowrule = float true, center true,match:class ^(.*)[Dd]ialog(.*)$

# common modals
windowrule = float true,match:title ^(Confirm to replace files)$
windowrule = float true,match:title ^(File Operation Progress)$
windowrule = float true,match:class ^(xdg-desktop-portal-gtk)$
windowrule = float true,match:class ^(xdg-desktop-portal-hyprland)$
windowrule = float true, match:title ^(branchdialog)$
windowrule = float true, center true,size 622 652, match:class clipse
windowrule = persistent_size on,suppress_event maximize, match:class .*
