windowrule = workspace 1,match:class ^(kitty)$
windowrule = workspace 2,match:class ^(zen|brave-browser|google-chrome)$
windowrule = workspace 3,match:class ^(cursor|neovide)$
windowrule = workspace 4,match:class ^(spotify|obsidian)$
windowrule = workspace 5,match:class ^(discord)$
windowrule = workspace 6,match:class ^(pcmanfm)$
